version: 2
jobs:
  build:
    working_directory: /src
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - restore_cache:
          key: v1-nix-store-{{ checksum "default.nix" }}
      - run: nix-build --cores 0 -j auto
      - save_cache:
          key: v1-nix-store-{{ checksum "default.nix" }}
          when: always
          paths:
            - /nix
