version: 2
jobs:
  build:
    working_directory: /src
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - restore_cache:
          key: nix-store
      - run: nix-build --cores 0 -j auto
      - save_cache:
          key: nix-store
          when: always
          paths:
            - /nix
